### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by enasr** [alexandrebagio/CodeIgniter3-sybase-driver#1]
Hi Alex,

How can I use it on database config.

I use the following:

    $db['default'] = array(
    	'dsn'	=> '',
    	'hostname' => '192.168.60.1:5000',
    	'username' => 'sa',
    	'password' => 'ultra',
    	'database' => 'goonline',
    	'dbdriver' => 'sybase',
    );

but got Invalid DB driver
Regards

**Comment by alexandrebagio** [comment]
Hi Enasr,
You need to install a module for PHP.
Take a look at this website http://scn.sap.com/docs/DOC-40537 

See you,

**Comment by enasr** [comment]
Hi Alex,

Thanks for your reply.

Is it also possible to use it in ASE Express Edition (linux)?  Can you extend some help in configuring my (Fedora) Linux to connect with ASE server.

My apologies, I tried many times installing Sybase ASE and used it in CodeIgniter but I was not successfull.

With a heart.
